object Fields {
    const val SERVICE_URL = "SERVICE_URL"
    const val SERVICE_PUBLIC_KEY = "SERVICE_PUBLIC_KEY" // optional
    const val SERVICE_CERTIFICATE_PATH = "SERVICE_CERTIFICATE_PATH" // optional

    const val FIREBASE_APP_INTEGRATION_KEY = "FIREBASE_APP_INTEGRATION_KEY"
}
